ProjectName: МАО
TermsOfUse: Правила
TermsOfUseTitle: Правила пользования сервисом

# ACCESS

WrongRequest: Неверный запрос
PleaseLogInText: Пожалуйста, войдите в систему для просмотра этой страницы
AccessDenied: Доступ запрещён
FormFailureErrorText: Форма содержит ошибки
NotFoundErrorText: Запрашиваемые данные не найдены

# PAGE TITLES

## COMMON

HomePageTitle: Главная страница
SignInPageTitle: Вход
SignUpPageTitle: Регистрация

## MANAGE

ListUserPageTitle: Пользователи
CreateUserPageTitle: Создание пользователя
UpdateUserPageTitle: Редактирование пользователя
DeleteUserPageTitle: Удаление пользователя

## OPERATORS

ProfileViewPageTitle: Кабинет

# MENU TITLES

## MANAGE

ManageUserMenuTitle: Управление пользователями

## OPERATORS

ProfileViewMenuTitle: Мой кабинет



# MISC COMMON PHRASES

SignOut: Выход

User: Пользователь
EmailAddress: Адрес эл.почты
Password: Пароль
PasswordConfirmation: Подтверждение пароля
WalletAddress: Адрес кошелька
Card: Карта
Phone: Телефон
Skype: Skype
WebSite: Веб.сайт
VkCom: ВКонтакте
Telegram: Telegram
Balance: Баланс

Save: Сохранить
Cancel: Отмена
ChangesSaved: Изменения сохранены

Withdraw: Вывод
Deposit: Пополнение

Alias: Ссылка
Title: Заголовок

Event: Событие
Execute: Исполнить
Executed: Исполнено

All: Все
Add: Добавить
Manage: Управление

Date: Дата
DateCreated: Дата создания

Fee: Комиссия
Received: Получено
Remainder: Остаток
Amount: Сумма
QuantityShort: Кол-во
Ratio: Курс
Details: Подробности

EmailConfirmedText: Проверка почты успешно пройдена!
EmailAlreadyConfirmedText: Проверка уже пройдена
Support: Тех.поддержка