ProjectName: МАО
TermsOfUse: Правила
TermsOfUseTitle: Правила пользования сервисом

# ACCESS

WrongRequest: Неверный запрос
PleaseLogInText: Пожалуйста, войдите в систему для просмотра этой страницы
AccessDenied: Доступ запрещён
FormFailureErrorText: Форма содержит ошибки
NotFoundErrorText: Запрашиваемые данные не найдены

# PAGE TITLES

## COMMON

HomePageTitle: Главная страница
SignInPageTitle: Вход
SignUpPageTitle: Регистрация

## MANAGE

ListUserPageTitle: Пользователи
CreateUserPageTitle: Создание пользователя
UpdateUserPageTitle: Редактирование пользователя
DeleteUserPageTitle: Удаление пользователя

## OPERATORS

ProfileViewPageTitle: Кабинет

# MENU TITLES

## MANAGE

ManageUserMenuTitle: Управление пользователями

## OPERATORS

ProfileViewMenuTitle: Мой кабинет



# MISC COMMON PHRASES
Save: Сохранить
Cancel: Отмена
ChangesSaved: Изменения сохранены

SignOut: Выход

User: Пользователь
EmailAddress: Адрес эл.почты
Password: Пароль
PasswordConfirmation: Подтверждение пароля
WalletAddress: Адрес кошелька
Alias: Ссылка
Title: Заголовок
Card: Карта
Phone: Телефон
Skype: Skype
WebSite: Веб.сайт
VkCom: ВКонтакте
Telegram: Telegram
Balance: Баланс
Event: Событие
Execute: Исполнить
Executed: Исполнено
Fee: Комиссия
Received: Получено
Remainder: Остаток
Withdraw: Вывод
Deposit: Пополнение
Amount: Сумма
QuantityShort: Кол-во
All: Все
Add: Добавить
Manage: Управление
Date: Дата
DateCreated: Дата создания
Details: Подробности
Ratio: Курс

EmailConfirmedText: Проверка почты успешно пройдена!
EmailAlreadyConfirmedText: Проверка уже пройдена
Support: Тех.поддержка